/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProdutoController;
import exceptions.ProductInvalid;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CadastrarProd extends javax.swing.JFrame {

    private TelaPrincipal telaPrincipal;

    /**
     * Creates new form CadastrarProd
     */
    public CadastrarProd(TelaPrincipal telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextoNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextoDescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextoPreco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextoQuantidade = new javax.swing.JTextField();
        BotaoCancelar = new javax.swing.JButton();
        BotaoCriar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Descrição");

        jLabel3.setText("Preço");

        jLabel4.setText("Quantidade");

        BotaoCancelar.setBackground(new java.awt.Color(234, 40, 40));
        BotaoCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotaoCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoCancelar.setText("CANCELAR");
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });

        BotaoCriar.setBackground(new java.awt.Color(48, 131, 214));
        BotaoCriar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotaoCriar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoCriar.setText("CRIAR");
        BotaoCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCriarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(TextoNome)
                    .addComponent(TextoDescricao)
                    .addComponent(TextoPreco)
                    .addComponent(TextoQuantidade)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoCriar, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCancelar)
                    .addComponent(BotaoCriar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_BotaoCancelarActionPerformed

    private void BotaoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCriarActionPerformed
        try{
            ProdutoController pc = new ProdutoController();
            
            String nome = TextoNome.getText();
            String descricao = TextoDescricao.getText();
            double valor = Double.parseDouble(TextoPreco.getText());
            int qnt = Integer.parseInt(TextoQuantidade.getText());
            
            pc.addProduto(nome, descricao, valor, qnt);
            telaPrincipal.updateListaEstoque();
            
            JOptionPane.showMessageDialog(
                this,
                "Produto adicionado ao estoque",
                "Sucesso!",
                JOptionPane.INFORMATION_MESSAGE
            );
            
            dispose();
        }
        catch (ProductInvalid e){
            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Erro ao adicionar o produto",
                JOptionPane.ERROR_MESSAGE
            );
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Erro no banco de dados",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_BotaoCriarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoCriar;
    private javax.swing.JTextField TextoDescricao;
    private javax.swing.JTextField TextoNome;
    private javax.swing.JTextField TextoPreco;
    private javax.swing.JTextField TextoQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
