/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatDarkLaf;
import controller.UsuarioController;
import exceptions.LoginInvalid;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setTitle("LOGIN");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TextoNomeUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BotaoLogin = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();
        newUserLabel = new javax.swing.JLabel();
        TextoSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setResizable(false);

        jLabel1.setText("Nome de Usuário");

        jLabel2.setText("Senha");

        BotaoLogin.setBackground(new java.awt.Color(48, 131, 214));
        BotaoLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotaoLogin.setForeground(new java.awt.Color(255, 255, 255));
        BotaoLogin.setText("LOGIN");
        BotaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLoginActionPerformed(evt);
            }
        });

        BotaoCancelar.setBackground(new java.awt.Color(234, 40, 40));
        BotaoCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotaoCancelar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoCancelar.setText("CANCELAR");
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });

        newUserLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        newUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        newUserLabel.setText("Cadastrar Novo Usuário");
        newUserLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newUserLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newUserLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newUserLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newUserLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BotaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(BotaoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(TextoSenha, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextoNomeUsuario, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(newUserLabel)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCancelar)
                    .addComponent(BotaoLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newUserLabel)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLoginActionPerformed
        try {
            UsuarioController uc = new UsuarioController();
            String user = TextoNomeUsuario.getText();
            String senha = TextoSenha.getText();
            Usuario loggedUser = uc.login(user, senha);
            
            TelaPrincipal novaTela = new TelaPrincipal(loggedUser);
            novaTela.setVisible(true);

            // Fecha a tela atual
            dispose();
        }
        catch (LoginInvalid e){
            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Erro na autenticação",
                JOptionPane.ERROR_MESSAGE
            );
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(
                this,
                e.getMessage(),
                "Erro no banco de dados",
                JOptionPane.ERROR_MESSAGE
            );
        }
        
    }//GEN-LAST:event_BotaoLoginActionPerformed

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
        TextoNomeUsuario.setText("");
        TextoSenha.setText("");
    }//GEN-LAST:event_BotaoCancelarActionPerformed

    private void newUserLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserLabelMouseEntered
        newUserLabel.setForeground(Color.CYAN);
    }//GEN-LAST:event_newUserLabelMouseEntered

    private void newUserLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserLabelMouseClicked
        CadastrarUsuario cadUser = new CadastrarUsuario();
        cadUser.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_newUserLabelMouseClicked

    private void newUserLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newUserLabelMouseExited
        newUserLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_newUserLabelMouseExited

    
    public static void main(String args[]) {
        try {
            FlatDarkLaf.setup();
        } catch (Exception ex) {
            System.err.println("Falha ao iniciar FlatLaf: " + ex.getMessage());
        }

        // Inicia a interface gráfica
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoLogin;
    private javax.swing.JTextField TextoNomeUsuario;
    private javax.swing.JPasswordField TextoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel newUserLabel;
    // End of variables declaration//GEN-END:variables
}
